# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-08 14:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(verbose_name='\u0410\u0434\u0440\u0435\u0441')),
                ('author', models.CharField(max_length=100, verbose_name='\u041a\u0442\u043e \u043f\u0440\u043e\u0432\u043e\u0434\u0438\u043b')),
                ('filename', models.CharField(max_length=100, verbose_name='\u0424\u0430\u0439\u043b')),
                ('operations', models.TextField(verbose_name='\u0422\u0440\u0430\u043d\u0441\u043b\u0438\u0442\u0435\u0440\u0430\u0446\u0438\u044f')),
                ('dt', models.DateField(verbose_name='\u0414\u0430\u0442\u0430 \u043f\u0440\u043e\u0432\u0435\u0434\u0435\u043d\u0438\u044f')),
            ],
            options={
                'verbose_name': '\u0417\u0430\u043f\u0438\u0441\u044c',
                'verbose_name_plural': '\u0417\u0430\u043f\u0438\u0441\u0438',
            },
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100, verbose_name='\u0421\u043b\u043e\u0432\u043e')),
                ('position', models.PositiveIntegerField(verbose_name='\u041f\u043e\u0437\u0438\u0446\u0438\u044f')),
                ('offset', models.PositiveIntegerField(help_text='\u043e\u0442 \u043d\u0430\u0447\u0430\u043b\u0430 \u0444\u0430\u0439\u043b\u0430, \u0432 \u0441\u0435\u043a\u0443\u043d\u0434\u0430\u0445', verbose_name='\u0421\u043c\u0435\u0449\u0435\u043d\u0438\u0435')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Record', verbose_name='\u0417\u0430\u043f\u0438\u0441\u044c')),
            ],
            options={
                'verbose_name': '\u0421\u043b\u043e\u0432\u043e',
                'verbose_name_plural': '\u0421\u043b\u043e\u0432\u0430',
            },
        ),
        migrations.CreateModel(
            name='WordNormal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('normal', models.CharField(max_length=100, verbose_name='\u041d\u043e\u0440\u043c\u0430\u043b\u044c\u043d\u0430\u044f \u0444\u043e\u0440\u043c\u0430')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Word', verbose_name='\u0421\u043b\u043e\u0432\u043e')),
            ],
            options={
                'verbose_name': '\u041d\u043e\u0440\u043c\u0430\u043b\u044c\u043d\u0430\u044f \u0444\u043e\u0440\u043c\u0430',
                'verbose_name_plural': '\u041d\u043e\u0440\u043c\u0430\u043b\u044c\u043d\u044b\u0435 \u0444\u043e\u0440\u043c\u044b',
            },
        ),
    ]
