# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-08 16:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20170908_2134'),
    ]

    operations = [
        migrations.AddField(
            model_name='wordnormal',
            name='record',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.Record', verbose_name='\u0417\u0430\u043f\u0438\u0441\u044c'),
            preserve_default=False,
        ),
    ]
